package com.zxiaoyao.openai.api.completion.chat;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

/**
 * @Description A chat completion generated by OpenAI
 * 由 OpenAI 生成的聊天完成
 * @Author hlantian
 * @Date Created in 15:07 2023/10/8
 * @Version 1.0
 */
@Data
public class ChatCompletionChoice {

    /**
     * This index of this completion in the returned list.
     * 返回的列表中该完成的索引。
     */
    private Integer index;

    /**
     * The {@link ChatMessageRole#ASSISTANT} message or delta (when streaming) which was generated
     *
     * 已生成的 {@link ChatMessageRole#ASSISTANT} 消息或 delta（流式）消息
     */
    @JsonAlias("delta")
    private ChatMessage message;

    /**
     * The reason why GPT stopped generating, for example "length".
     * GPT 停止生成的原因，例如 "length"。
     */
    @JsonProperty("finish_reason")
    private String finishReason;
}
