package com.zxiaoyao.openai.api.edit;

import com.zxiaoyao.openai.api.Usage;
import lombok.Data;

import java.util.List;

/**
 * @Description A list of edits generated by OpenAI
 * 由 OpenAI 生成的编辑列表
 * https://beta.openai.com/docs/api-reference/edits/create
 * @Author hlantian
 * @Date Created in 14:16 2023/10/8
 * @Version 1.0
 */
@Data
public class EditResult {

    /**
     * The type of object returned, should be "edit"
     * 返回对象的类型，应为 "edit"
     */
    private String object;

    /**
     * The creation time in epoch milliseconds.
     * 创建时间（以毫秒为单位）。
     */
    private long created;

    /**
     * A list of generated edits.
     * 生成的编辑列表。
     */
    private List<EditChoice> choices;

    /**
     * The API usage for this request
     * 该请求的 API 使用情况
     */
    private Usage usage;
}
