package com.zxiaoyao.openai.api.edit;

import lombok.Data;

/**
 * @Description An edit generated by OpenAi
 * 由 OpenAi 生成的编辑
 * https://beta.openai.com/docs/api-reference/edits/create
 * @Author hlantian
 * @Date Created in 14:08 2023/10/8
 * @Version 1.0
 */
@Data
public class EditChoice {

    /**
     * The edited text.
     * 经编辑的文本。
     */
    private String text;

    /**
     * This index of this completion in the returned list.
     * 返回的列表中该完成的索引。
     */
    private Integer index;
}
